application: lunchengine
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /scripts
  static_dir: scripts  

- url: /.*
  script: lunchengine.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: 2.6